name: Create and publish a package
on:
    push:
        branches:
            - main

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Runtime versions
              run: |
                  docker -v
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_TOKEN }}
            - name: Build docker image
              run: |
                  docker build \
                    -t ghcr.io/${{ github.repository }}:${{ github.sha }} \
                    -t ghcr.io/${{ github.repository }}:latest \
                    .
            - name: Push docker image to Github Package Registry
              run: |
                  docker push --all-tags ghcr.io/${{ github.repository }}
